name: OneStepToThePicture

variables:
  appVersion: &app_version "1.0.0"

options:
  groupSortPosition: top
  generateEmptyDirectories: true
  createIntermediateGroups: true
  developmentLanguage: en

targets:
  OneStepToThePicture:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - path: Source
    scheme: {}
    settings:
        base:
            TARGETED_DEVICE_FAMILY: 1
            MARKETING_VERSION: *app_version
            CURRENT_PROJECT_VERSION: "1"
            SWIFT_VERSION: "5"
            PRODUCT_NAME: Image Gallery App
            PRODUCT_BUNDLE_IDENTIFIER: ilya.grishuk-intexsoft.com.OneStepToThePicture
    info:
      path: Source/Info.plist
      properties:
        UILaunchScreen: LaunchScreen.storyboard
        UIRequiresFullScreen: true
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UIViewControllerBasedStatusBarAppearance: false
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        CFBundleDisplayName: $(BUNDLE_DISPLAY_NAME)
        UIApplicationSupportsIndirectInputEvents: true
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: *app_version
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        ITSAppUsesNonExemptEncryption: false
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
                
    dependencies:
     - package: Utils
     - package: SnapKit
     - package: Moya
     - package: Kingfisher
     - package: IQKeyboardManagerSwift
      
packages:
  Utils:
    url: https://github.com/MobileUpLLC/Utils
    exactVersion: 0.3.1
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    exactVersion: 5.6.0
  Moya:
    url: https://github.com/Moya/Moya.git
    exactVersion: 15.0.3
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    exactVersion: 7.10.0
  IQKeyboardManagerSwift:
    url: https://github.com/hackiftekhar/IQKeyboardManager.git
    exactVersion: 6.5.16
